### ISSUE TITLE
custom_content MultiQC module broke

### ISSUE THREAD

**Issue by JohannesKersting** [MultiQC/MultiQC#2916] opened 2024-10-11 15:57 UTC
### Description of bug

Hello :)

Encountered an error after updating an nf-core pipeline template. The error suggested to report it here:

Multiqc fails with custom content. It looks like the files are not properly matched to the configuration sections in the multiqc config file.

Attached is the config file (since I don't think this is really about the input file) and the input file causing the trouble.

### File that triggers the error

[topology_mqc.zip](https://github.com/user-attachments/files/17344885/topology_mqc.zip)
[multiqc_config.zip](https://github.com/user-attachments/files/17344934/multiqc_config.zip)

### MultiQC Error log

```console
nextflow .commands.sh:

#!/usr/bin/env bash

set -e # Exit if a tool returns a non-zero status/exit code
set -u # Treat unset variables and parameters as an error
set -o pipefail # Returns the status of the last command to exit with a non-zero status or zero if all successfully execute
set -C # No clobber - prevent output redirection from overwriting files.

multiqc \
    --force \
     \
    --config multiqc_config.yml \
     \
     \
     \
     \
     \
    .

cat <<-END_VERSIONS > versions.yml
"REPO4EU_MODULEDISCOVERY:MODULEDISCOVERY:MULTIQC":
    multiqc: $( multiqc --version | sed -e "s/multiqc, version //g" )
END_VERSIONS

log:

/// MultiQC 🔍 v1.25.1
  
              config | Loading config settings from: multiqc_config.yml
         file_search | Search path: /home/johannes/workspace/modulediscovery/modulediscovery/work/30/77826e79b6743769737df6ac503100
         file_search | Only using modules: custom_content
  
  ╭───────────── Oops! The 'custom_content' MultiQC module broke... ─────────────╮
  │ Please copy this log and report it at                                        │
  │ https://github.com/MultiQC/MultiQC/issues                                    │
  │ Please attach a file that triggers the error. The last file found was:       │
  │ 7/topology_mqc.tsv                                                           │
  │                                                                              │
  │ Traceback (most recent call last):                                           │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/core/exec_modules.py │
  │     these_modules: Union[BaseMultiqcModule, List[BaseMultiqcModule]] = modul │
  │                                                                        ^^^^^ │
  │   File "/usr/local/lib/python3.12/site-packages/multiqc/modules/custom_conte │
  │     assert isinstance(d, dict), (c_id, f["fn"], f["root"])                   │
  │            ^^^^^^^^^^^^^^^^^^^                                               │
  │ AssertionError: ('shared_nodes', 'topology_mqc.tsv', '7')                    │
  │                                                                              │
  ╰──────────────────────────────────────────────────────────────────────────────╯
             multiqc | No analysis results found. Cleaning up…
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://docs.seqera.io/multiqc/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment] 2024-10-15 09:30
Hi!

The zip archives you attached contain symlinks, not the actual files. Could you please re-send attachments?

Thank you and sorry about the issue!

**Comment by JohannesKersting** [comment] 2024-10-15 12:28
[topology_mqc.zip](https://github.com/user-attachments/files/17377963/topology_mqc.zip)
[multiqc_config.zip](https://github.com/user-attachments/files/17377964/multiqc_config.zip)
Hi,

Thanks for the fast reply and for providing/maintaining this awesome tool!
Attached the real files this time :) Hope this helps! Let me know, if you need anything else

Thank you very much!
[topology_mqc.zip](https://github.com/user-attachments/files/17377986/topology_mqc.zip)
[multiqc_config.zip](https://github.com/user-attachments/files/17377987/multiqc_config.zip)

**Comment by jonbra** [comment] 2024-10-15 17:09
I have a similar problem with a custom csv file. Using MultiQC version 1.25

**Comment by vladsavelyev** [comment] 2024-10-16 11:07
@JohannesKersting, would you be able a `shared_nodes` file as well? Can't reproduce the problem without this one. Thank you 🙏

**Comment by JohannesKersting** [comment] 2024-10-16 11:53
@vladsavelyev 
sure, attached the whole nextflow work directory. Since if I run it multiple times, it fails for different file combinations
[workdir.zip](https://github.com/user-attachments/files/17395177/workdir.zip)

**Comment by vladsavelyev** [comment] 2024-10-16 20:12
Thanks a lot for sharing the folder! That helped a lot. There is indeed was a regression introduced recently. Fixed with: https://github.com/MultiQC/MultiQC/pull/2921 Will probably make a patch release next week.

**Closed** 2024-10-16 22:00 UTC
Labels: bug: core, custom-content

**Comment by JohannesKersting** [comment] 2024-10-17 07:12
Thank you very much for fixing this so fast!

**Comment by schorlton-bugseq** [comment] 2024-10-18 02:41
@vladsavelyev , could a test be introduced to handle this case and prevent it from cropping up again?
