### ISSUE TITLE
CollectWgsMetrics from Picard not picked up in latest version

### ISSUE THREAD

**Issue by mathiasbio** [MultiQC/MultiQC#2607] opened 2024-06-05 07:47 UTC
### Description of bug

In version 1.18 of MultiQC CollectWgsMetrics from Picard is picked up, but in the two latest versions I've checked 1.22.1 and 1.22.2 it's not detected. Neither from the Sentieon module (WgsMetricsAlgo) or from Picard (CollectWgsMetrics)

### File that triggers the error

[568664_picard_wgs_metrics.txt](https://github.com/user-attachments/files/15578379/568664_picard_wgs_metrics.txt)

### MultiQC Error log

```console
/// MultiQC 🔍 v1.22.2

[2024-06-05 09:46:45] multiqc.core.update_config                         [DEBUG  ]  This is MultiQC v1.22.2
[2024-06-05 09:46:45] multiqc.core.update_config                         [DEBUG  ]  Running Python 3.11.3 (main, May 23 2023, 13:34:03) [GCC 10.2.1 20210110]
[2024-06-05 09:46:45] urllib3.connectionpool                             [DEBUG  ]  Starting new HTTPS connection (1): api.multiqc.info:443
[2024-06-05 09:46:45] urllib3.connectionpool                             [DEBUG  ]  https://api.multiqc.info:443 "GET /version?version_multiqc=1.22.2&version_python=3.11.3&operating_system=Linux&is_docker=False&is_singularity=True&is_conda=False&is_ci=False&is_notebook=False HTTP/1.1" 200 182
[2024-06-05 09:46:45] multiqc.core.version_check                         [DEBUG  ]  Latest MultiQC version is v1.22.2, released 2024-05-31
[2024-06-05 09:46:45] multiqc.multiqc                                    [DEBUG  ]  Working dir : /home/proj/development/cancer/mathias/implementations/updatemultiqc/test2
[2024-06-05 09:46:45] multiqc.multiqc                                    [DEBUG  ]  Template    : default
[2024-06-05 09:46:45] multiqc.report                                     [DEBUG  ]  Using temporary directory: /home/mathias.johansson/tmp/tmp5cy0gnou
[2024-06-05 09:46:45] multiqc.multiqc                                    [DEBUG  ]  Command used: /usr/local/bin/multiqc -o multiqc/ qc/ -v
[2024-06-05 09:46:45] multiqc.core.file_search                           [DEBUG  ]  Analysing modules: custom_content, ccs, ngsderive, purple, conpair, isoseq, lima, peddy, somalier, methylqa, mosdepth, phantompeakqualtools, qualimap, bamdst, preseq, hifiasm, quast, qorts, rna_seqc, rockhopper, rsem, rseqc, busco, bustools, goleft_indexcov, gffcompare, disambiguate, supernova, deeptools, sargasso, verifybamid, mirtrace, happy, mirtop, sambamba, gopeaks, homer, hops, macs2, theta2, snpeff, gatk, htseq, bcftools, featureCounts, fgbio, dragen, dragen_fastqc, dedup, pbmarkdup, damageprofiler, mapdamage, biobambam2, jcvi, mtnucratio, picard, vep, bakta, prokka, qc3C, nanostat, samblaster, samtools, sexdeterrmine, seqera_cli, eigenstratdatabasetools, bamtools, jellyfish, vcftools, longranger, stacks, varscan2, snippy, umitools, truvari, megahit, bbmap, bismark, biscuit, diamond, hicexplorer, hicup, hicpro, salmon, kallisto, slamdunk, star, hisat2, tophat, bowtie2, bowtie1, hostile, cellranger, snpsplit, odgi, pangolin, nextclade, freyja, humid, kat, leehom, librarian, nonpareil, adapterremoval, bbduk, clipandmerge, cutadapt, flexbar, sourmash, kaiju, bracken, kraken, malt, motus, trimmomatic, sickle, skewer, sortmerna, biobloomtools, fastq_screen, afterqc, fastp, fastqc, sequali, filtlong, prinseqplusplus, pychopper, porechop, pycoqc, minionqc, anglerfish, multivcfanalyzer, clusterflow, checkqc, bcl2fastq, bclconvert, interop, ivar, flash, seqyclean, optitype, whatshap, spaceranger, xenome, xengsort, metaphlan, seqwho
[2024-06-05 09:46:45] multiqc.core.file_search                           [INFO   ]  Search path: /home/proj/development/cancer/mathias/implementations/updatemultiqc/test2/qc
[2024-06-05 09:46:45] multiqc.report                                     [DEBUG  ]  Ignored 1 search patterns as didn't match running modules.
         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 2/2  
[2024-06-05 09:46:45] multiqc.report                                     [DEBUG  ]  Summary of files that were skipped by the search: |skipped_module_specific_max_filesize: 12|, |skipped_no_match: 2|
[2024-06-05 09:46:45] multiqc.core.exec_modules                          [DEBUG  ]  Running module: custom_content
[2024-06-05 09:46:45] multiqc.core.exec_modules                          [DEBUG  ]  No samples found: custom_content
[2024-06-05 09:46:45] multiqc.core.software_versions                     [DEBUG  ]  Reading software versions from config.software_versions
[2024-06-05 09:46:45] multiqc.core.exec_modules                          [WARNING]  No analysis results found. Cleaning up…
[2024-06-05 09:46:45] multiqc.core.exec_modules                          [INFO   ]  MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by bj-w** [comment] 2024-06-05 16:07
I've also found MultiQC v1.22.1 does not identify the output for CollectRnaSeqMetrics either. Rolling back to v1.18 fixes this.

**Comment by vladsavelyev** [comment] 2024-06-05 18:53
@rhpvorderman, it looks like it was a regression after the line block iterator introduction. The `contents_re` patterns previously assumed that they would be matched against each line separately, but since now they are matched against the multi-line blocks, some patterns from https://github.com/MultiQC/MultiQC/blob/main/multiqc/search_patterns.yaml#L677-L678 like `^(feature\tcount|\w+.*\t\d+)$` (requiring exact line) and `"## METRICS CLASS.*WgsMetrics"` (doesn't occur on the first line) fail. Do you have any thoughts on how to account for such patterns?

**Comment by vladsavelyev** [comment] 2024-06-05 19:58
The fix looks pretty straightforward - change `.match` to `.search` to allow matches in multi-line blocks. Plus, replace `$` in patterns with `\n`. Addressed with https://github.com/MultiQC/MultiQC/pull/2609

**Comment by vladsavelyev** [comment] 2024-06-05 22:23
Fixed with https://github.com/MultiQC/MultiQC/pull/2610, will release a patch release soon.

**Closed** 2024-06-05 22:22 UTC
Labels: bug: core

**Comment by rhpvorderman** [comment] 2024-06-07 08:11
Ah, that's so unfortunate. I didn't catch this. Sorry!
Luckily the performance improvement for the line iterator still holds for the non-regex patterns which are the majority.
