### ISSUE TITLE
Custom images, showing only one image

### ISSUE THREAD

**Issue by lukatop** [MultiQC/MultiQC#1796] opened 2022-11-09 18:45 UTC
### Description of bug

Hi all, first of thank you for a great tool! It can do a lot of things, including my own data in it. 

However, although I have 5 samples, it loads custom tables fine but for images, it loads only the last one and embeds it in the report. I know including all images can create a large HTML, but I want to see the report with all the things added. 

I assume I am doing something wrong in the config file. I am attaching redacted config to skip unnecessary lines which are working fine, like mentioned custom tables.  
Can you take a look and tell me what is going on? 

### File that triggers the error

[pipeline_config_images_only.txt](https://github.com/ewels/MultiQC/files/9974158/pipeline_config_images_only.txt)

### MultiQC Error log

```console
/// MultiQC 🔍 | v1.13

|           multiqc | Excluding modules 'snippy'
|           multiqc | Search path : /Users/lukatopalovic/PycharmProjects/MultiQC/multiqc
|           multiqc | Search path : /Users/lukatopalovic/Downloads/multiqc_inputs
|            report | Error: MultiQC is running in source code directory! multiqc
|            report | Please see the docs for how to use MultiQC: https://multiqc.info/docs/#running-multiqc
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 66/66  
|    custom_content | plasma_cells_genes_expression: Found 1 sample (image)
|    custom_content | igblast_vscore_dist: Found 1 sample (image)
|    custom_content | trinity_contig_dist: Found 1 sample (image)
|             fastp | Found 5 reports
|            fastqc | Found 10 reports
|           multiqc | Compressing plot data
|           multiqc | Deleting    : multiqc_report.html   (-f was specified)
|           multiqc | Deleting    : multiqc_data   (-f was specified)
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

**Comment by ewels** [comment] 2022-11-09 20:39
It's very difficult to know without playing around myself, and for that I need a complete reproducible example with input files.

However, when you are expecting several things in a report and only get one, it's nearly always because the sample identifiers end up being the same and are overwritten (see [docs](https://multiqc.info/docs/#not-enough-samples-found)). Though for custom content it can also be other things, as the scope of what is possible is so wide.

**Comment by lukatop** [comment] 2022-11-09 20:58
Hi Phil, thanks for a quick reply! Here is the link to complete data: https://www.dropbox.com/s/gwrn0mc1okoff7k/multiqc_inputs.zip?dl=0

I couldn't share it here, I added whole config file in the zip folder. 

Here is the log of the run with data I shared: 

```
  /// MultiQC 🔍 | v1.13

|           multiqc | Excluding modules 'snippy'
|           multiqc | Search path : /Users/lukatopalovic/PycharmProjects/MultiQC/multiqc
|           multiqc | Search path : /Users/lukatopalovic/Desktop/multiqc_inputs
|            report | Error: MultiQC is running in source code directory! multiqc
|            report | Please see the docs for how to use MultiQC: https://multiqc.info/docs/#running-multiqc
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 67/67  
|    custom_content | mapping_stats: Found 5 samples (table)
|    custom_content | kraken_stats: Found 5 samples (table)
|    custom_content | trinity_stats: Found 5 samples (table)
|    custom_content | igblast_stats: Found 5 samples (table)
|    custom_content | epic_immune_cells_fraction: Found 5 samples (table)
|    custom_content | mcpcounter_immune_cells_scores: Found 5 samples (table)
|    custom_content | plasma_cells_genes_expression: Found 1 sample (image)
|    custom_content | igblast_vscore_dist: Found 1 sample (image)
|    custom_content | trinity_contig_dist: Found 1 sample (image)
|             fastp | Found 5 reports
|            fastqc | Found 10 reports
|           multiqc | Compressing plot data
|           multiqc | Deleting    : multiqc_report.html   (-f was specified)
|           multiqc | Deleting    : multiqc_data   (-f was specified)
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

**Comment by lukatop** [comment] 2022-11-09 22:57
I attached it here, sorry for the inconvenience. 
[multiqc_inputs.zip](https://github.com/ewels/MultiQC/files/9975766/multiqc_inputs.zip)

**Comment by lukatop** [comment] 2022-11-18 11:12
Hi @ewels, any update on this?

**Comment by ewels** [comment] 2022-12-15 16:22
Haven't had a chance to look yet sorry. Will do so when I get a moment..

**Comment by minhtrung1997** [comment] 2023-05-19 09:23
https://github.com/ewels/MultiQC/issues/798

It's solved !

**Comment by ewels** [comment] 2023-05-20 22:14
Thanks @minhtrung1997 - that issue is about supporting Custom Content images in MultiQC reports. This issue is about only 1 image showing up when multiple were provided, so slightly different.

@lukatop - I think the problem is that you're specifying the section ID. The code only supports a single image per section, so it gets overwritten every time. It's not an easy fix unfortunately - the simplest thing to do will be to rename your images to `*_mqc.png` and let MultiQC discover them itself. Then each image will get its own ID and section and won't get overwritten. However, then  it will be difficult to customise the report.

Do you really have no raw data for these plots? Using MultiQC to generate the plots would be a better end user experience and a lot easier for you. If you look in the RSeQC module (from memory) I think it takes R scripts used to generate image plots and pulls the raw data from there to replot in MultiQC. There are sometimes ways if you look hard 😅

**Comment by vladsavelyev** [comment] 2024-08-18 16:02
Embedding static images is not the main MultiQC usecase, as it's itself intended to generate interactive plots. As Phil said, problems comes from images pulling IDs from file names, and just renaming files will be a workaround. So closing now.

**Closed by vladsavelyev** 2024-08-18 16:02 UTC
Labels: custom-content
