### ISSUE TITLE
MultiQC 1.15+ lost all coverage_mqc-generalstats-dragen_coverage except one

### ISSUE THREAD

**Issue by Stikus** [MultiQC/MultiQC#2332] opened 2024-02-15 09:43 UTC
### Description of bug

In `MultiQC 1.15` `General Statistics` table lost several DRAGEN coverage columns, and they don't come back:

-  1.14 → 1.15
![image](https://github.com/MultiQC/MultiQC/assets/41360525/46c5f6c0-5c14-43fe-bc5d-e6584965545b)
![image](https://github.com/MultiQC/MultiQC/assets/41360525/ce307aae-1235-4131-b391-d88875f61958)

- 1.14 → 1.20
![image](https://github.com/MultiQC/MultiQC/assets/41360525/a9ffaaed-b300-43f7-bd28-72b6196917c0)

This can be seen in `multiqc_data.json` too:  
-  1.14 → 1.15
![image](https://github.com/MultiQC/MultiQC/assets/41360525/ab292846-ed8f-4149-a615-34f56ae469fc)
- 1.14 → 1.20
![image](https://github.com/MultiQC/MultiQC/assets/41360525/30ab7a81-7317-477b-8db8-b60c3ceef6c9)

For some reason, MultiQC 1.15+ find 2 reports instead of one (can be seen in MultiQC log below) - 2 reports for each sample if we plot multiple samples.

### File that triggers the error

[00050101.dragen.zip](https://github.com/MultiQC/MultiQC/files/14294281/00050101.dragen.zip)

### MultiQC Error log

```console
bio@bisa07:/mnt/ubm01-raid10/Stik/biotools/multiqc$ docker run --rm -it -v $PWD/inputs_dragen:/inputs -v $PWD/out_1.14_dragen:/outputs --entrypoint multiqc multiqc:v1.8.0 -o /outputs /inputs

  /// MultiQC 🔍 | v1.14

|           multiqc | MultiQC Version v1.20 now available!
|           multiqc | Search path : /inputs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 11/11
|            dragen | Found 1 reports
|           multiqc | Compressing plot data
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
bio@bisa07:/mnt/ubm01-raid10/Stik/biotools/multiqc$ docker run --rm -it -v $PWD/inputs_dragen:/inputs -v $PWD/out_1.15_dragen:/outputs --entrypoint multiqc multiqc:v1.8.2 -o /outputs /inputs

  /// MultiQC 🔍 | v1.15

|           multiqc | MultiQC Version v1.20 now available!
|           multiqc | Search path : /inputs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 11/11
|            dragen | Found 2 reports
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
bio@bisa07:/mnt/ubm01-raid10/Stik/biotools/multiqc$ docker run --rm -it -v $PWD/inputs_dragen:/inputs -v $PWD/out_1.20_dragen:/outputs --entrypoint multiqc multiqc:v2.1.0 -o /outputs /inputs

  /// MultiQC 🔍 | v1.20

|           multiqc | Search path : /inputs
|         searching | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 100% 11/11
|            dragen | Found 2 reports
|           multiqc | Report      : multiqc_report.html
|           multiqc | Data        : multiqc_data
|           multiqc | MultiQC complete
```

### Before submitting

- [X] I have read the [troubleshooting documentation](https://multiqc.info/docs/usage/troubleshooting/).
- [X] I am using the latest release of MultiQC.
- [X] I have included a full MultiQC log, not truncated.
- [X] I have attached an input file (**.zip** if necessary) that triggers the error.

**Comment by vladsavelyev** [comment] 2024-02-15 18:35
Hey @Just-Roma, @alexiswl , would you be able to take a look? Seems to happen after the large PR merge last May: https://github.com/MultiQC/MultiQC/pull/1880 

I confirm that I can reproduce with `test_data/data/modules/dragen/alignment/TEST.wgs_coverage_metrics.csv`. 

Seem to stem from some discrepancy around the phenotype/target prefixes/suffixes, e.g. the header has `"average alignment coverage over region"` while the code prepends it with `"wgs "`, resulting in mismatch. But I can't understand what would be the right fix there :(

**Comment by Just-Roma** [comment] 2024-02-15 21:03
Hey, I have tested the [00050101.dragen](https://github.com/MultiQC/MultiQC/files/14294281/00050101.dragen.zip) with v1.15 and v1.21. The issue was already discussed [here](https://github.com/MultiQC/MultiQC/issues/1952).  
You just need to adjust the `"exclude"` config in the dragen/coverage_metrics.py  

Either set it to False in the `SINGLE_HEADER` var to have all metrics in the common plot/json:  

![exclude1](https://github.com/MultiQC/MultiQC/assets/64587275/a6ac75eb-1293-4d12-b377-30295fcce75f)  

Or, if you want to have only a subset of metrics in the common plot/json, add `"exclude": False` to some metrics in the `METRICS` var. The `"average alignment coverage over region"` metric is the only one shown in the global plot by default:  

![exclude2](https://github.com/MultiQC/MultiQC/assets/64587275/47a7b825-ef9e-425d-88e0-cfd73152044e)  

Reinstall the multiqc after redefining.  

P.S Probably not needed but it is also possible to have more fine-tuned table. The `REGIONS` var and its single regions can be used to adjust region-specific configs, including the `"exclude"` config.

**Comment by alexiswl** [comment] 2024-02-15 21:23
@Just-Roma is it possible to set this up for this to be configurable in the runtime config? 

If a user is running the standard docker image, they won't be able to update dragen/coverage_metrics.py.

**Comment by Just-Roma** [comment] 2024-02-15 22:05
@alexiswl no unfortunately not. Must be implemented somehow. I have never tested multiqc with docker, so can not really help here. Probably the only way currently to solve the issue is to create an image with an updated file.

**Comment by vladsavelyev** [comment] 2024-02-15 22:11
Thanks for the quick response! 

We shouldn't be relying on configuring anything directly inside the source code. Configuration should be done through global MultiQC YAML config. 

But in this case, I think those coverage metrics should be displayed by default somewhere, if not hidden in general stats, then in a separate section.

**Comment by vladsavelyev** [comment] 2024-02-15 22:21
Ah, I realised that all coverage metrics are actually available in a separate table in a section "WGS Coverage Metrics" below. @Stikus can you confirm it works for you?

But I think we might want to add some more coverage hidden metrics into the general stats table. There are many `mapping` metrics there, and only one from the `coverage` section.

**Comment by Just-Roma** [comment] 2024-02-15 22:41
Suggestions: 
1) Add an additional block in the make_coverage_headers func on the line 1226. The block would handle the extraction of configs from yaml and assign it to the headers.
2) Just restore the common table's state as it was in v1.14. Tbh i have no idea what is relevant for users. If those metrics are the only wanted ones, then it is much easier to just restore them.

**Comment by vladsavelyev** [comment] 2024-02-15 23:09
I think we can just restore a few commonly used metrics. And `Depth` is worth showing by default in general stats. 

<img width="1066" alt="Screenshot 2024-02-16 at 00 07 44" src="https://github.com/MultiQC/MultiQC/assets/1575412/41aefcbc-5980-497b-b055-c629e32343f6">

<hr>
<hr>

The rest we have in a separate section, so users can go there if needed. 

<img width="1154" alt="Screenshot 2024-02-16 at 00 08 09" src="https://github.com/MultiQC/MultiQC/assets/1575412/92a446d8-ada6-415c-8651-ddaf9ae8c05d">


<hr>
<hr>

Done that with https://github.com/MultiQC/MultiQC/pull/2341

@Stikus, let me know if it sounds good!

**Comment by Stikus** [comment] 2024-02-16 07:32
@vladsavelyev Thanks! Looks good.

And what about 2 reports per sample?
![image](https://github.com/MultiQC/MultiQC/assets/41360525/185910f5-62c6-43ec-a0ec-d4d8d430da59)

**Closed** 2024-02-18 17:03 UTC
Labels: dragen

**Comment by vladsavelyev** [comment] 2024-02-18 17:08
@Stikus, oh, right, it's showing "TEST_wgs" as a separate sample (because we can expect to have coverage data for different targets and phenotypes). Fixed it to count the number of actual samples! Thanks for pointing to this.
