### ISSUE TITLE
Soliciting tool for MultiQC

### ISSUE THREAD

**Issue by BiomedicLJZ** [MultiQC/MultiQC#3036] opened 2024-12-31 05:19 UTC
### Name of the tool

ANNOVAR

### Tool homepage

https://annovar.openbioinformatics.org/en/latest/

### Tool description

The tool is one of the most used tools for variant annotation

### Tool output

[output.hg19_multianno.txt](https://github.com/user-attachments/files/18279405/output.hg19_multianno.txt)

### Log filename pattern

output.hg19_multianno.txt

### Data suitable for MultiQC plot(s)

Probably plots for the variants detected.

### Most interesting data for the General Stats table

Listing of all the genes involved in the variants

### Before submitting

- [X] I have included example data (zipped, not pasted) that can be used to write the module.

**Comment by ewels** [comment] 2024-12-31 11:24
Duplicate of https://github.com/MultiQC/MultiQC/issues/822

Thanks though, the additional test data helps and we'll try to prioritise this one more.

**Closed by ewels** 2024-12-31 11:24 UTC
Labels: module: new
